### ISSUE TITLE
GameStates are cached

### ISSUE THREAD

**Issue by Blecki** [CompletelyFairGames/dwarfcorp#11]
I'm not seeing the benefit to this, and it means that all the menu states need to be re-entrant. It doesn't seem like it would be costly to recreate the auxiliary states on demand. It may also simplify the states themselves.

Also, it does not seem wise to use MainMenuState as both the launch menu and the in game pause menu.

**Comment by yueranyuan** [comment]
I haven't looked at the the nice aspect is that it keeps PlayState cached (which we of course want). But I suppose PlayState can be cached explicitly while every other state is not. Potentially it could be nice to cache EconomyState as well depending on how complex it gets. But as I mentioned in the Gitter, I also don't see the harm - these states are not active and I don't think the memory usage is particularly high for any of them. And on the other hand it does allow fast switching between states and obviate the need to do any clean up between state switches (although I don't think state switching speed and clean up is really an issue)

I think this is situation where refactoring would mainly be for stylistic rather than performance/functionality reasons.

**Comment by mklingen** [comment]
You're right about this. I don't see why it needs to be this way either. Instead the state stack should directly store the states. It should actually look like this:

At the beginning of the game:
- MainMenuState

At world generation you can pop to go back to the main menu:
- WorldGeneratorState
-  MainMenuState

During gameplay, the stack should be completely erased leaving only PlayState:
- PlayState

But it is possible to do other things, like hire employees:
- EconomyState
- PlayState

Or open up a pause menu:
- PauseState
- PlayState

But then when higher states are popped, they should be erased. (I think right now they are still in the list of all states, which is totally bonkers wrong).

**Comment by mklingen** [comment]
This has been fixed.
