### ISSUE TITLE
Monolithic class PlayState

### ISSUE THREAD

**Issue by Blecki** [CompletelyFairGames/dwarfcorp#12]
This needs to be split up.

My suggestion: Start by separating the 'world' into a simulation class that handles keeping track of the world and the dwarves and factions and what not, if such a thing doesn't already exist.
Then make a class responsible for building the chunks and what not.
And get the particle system initialization out of there.
PlayState should be left as the UI interaction logic and little else.

**Comment by yueranyuan** [comment]
I agree that some refactoring would be welcome in a few places, although I wonder whether the current way it is setup is serviceable for now. In so far as I see it the reason PlayState is so large is that it mixes 3 different functions:

1) it creates and handles the game gui which is quite large. As you rightly point out - this probably has the most right to be in the PlayState class since it parallels the fact that every other GameState owns its own GUI (though the tools panel lives in MasterControls which I suppose is just as well given its atypical nature)

2) it initializes and handles the "world/simulation" as you call it. That includes initializing the particle system, the components system, the chunk system, liquids, shadows, arguably saving & loading etc. It is possible to imagine abstracting all of this out into a separate parent GameState e.g. WorldState (which has the advantage of handling drawing) or just a container WorldManager (which has the advantage of not requiring us to deepen the inheritance tree). In particular this separation of concerns would make sense if we hypothetically consider the "World" as a stand-alone reusable object - e.g. other game modes etc. where a simulation is running but the creatures, gui, scenario, etc. are completely different.

However, I will point out that there seem to be no plans for any other game modes and so since there are no other GameStates that really make use of a World, all we would accomplish with refactoring is a relocation of code from one file to another.

3) the non-world/simulation related but game-mode specific code. Mostly stuff related to Embarkment. This includes initializing the first embarkment and creating the balloon (large function). These represent the special way that the World is modified to setup a Game of Dwarfcorp (i.e. PlayState) - that is to say in contrast to some other imaginary uses of World (other game modes or whatever).

I can imagine both (1) and (3) remaining in the PlayState class or possibly (3) moving off into its own namespace (gamemode) or something. And while it makes sense to move (2), I do wonder whether its worth it at least in the present since it won't really be reused and it's not really a source of bugs.

**Comment by Blecki** [comment]
The main benefit of refactoring it will be making playstate easier to work with and easier to understand.

Sent from my HTC One on the Verizon Wireless 4G LTE network

----- Reply message -----

**Comment by DanoThom** [comment]
Have you guys (the primary devs) ever considered porting active development to the Unity engine? I made the jump from XNA a while back and Unity has really come along in leaps and bounds. It's a very comprehensive engine where I now feel you can be truly productive. 

As an example here's a 3D hobby DF-type prototype I hooked up in my free time over a few months last year :
https://www.youtube.com/playlist?list=PLPQAzIQMJVxwypdGnieRv-Bdy7TxBOoQj

Note: You'll notice I was using your tileset as a test placeholder while working on the blended terrain (which I couldn't quite get to work as well as yours).

PS: glad to see you guys are still working on this game!

**Comment by Blecki** [comment]
Your project looks nice.

I don't think switching to Unity is on anyone's mind, or that it is practical. There's a lot of game built and switching to unity means starting from scratch. Matt also just drummed up a bunch of people experienced with XNA...

That's us. We aren't the 'primary devs', we're just some jerks from Reddit who've come over to help.

**Comment by DanoThom** [comment]
I guess if the XNA talent has already been recruited then it makes sense to stay with it. It's just that with XNA you still feel like you have to fully build and round off most of the engine systems which is so time consuming and error prone.

I agree that there is a lot of game already built in DwarfCorp - however a large chunk of that code appears to mostly be for game systems which could be quite transferable. So apart from swapping out the base entity components for the Unity ones (and subsequently using Unity's gameObject component driven entity system instead) you'd probably only really need to do a fair bit of work on splitting up that large main shader file into something that Unity can consume.

Considering there is so much sprite work in DwarfCorp, apart from the normal benefits of comprehensive Physics and Rendering systems, you'd also benefit from great quality of life improvements and features like the sprite packers, packaging modules, animation and behaviour subsystems etc. The real time editor doesn't hurt either :) 
The cherry on top is obviously that all of the porting to other platforms is already in the box too if you need it. 

Note: However due to the prevalent use of the C# Parallel libraries for the Task system, of course it would only TRULY be worth considering for DwarfCorp when Unity properly fully finish the upgrade from .NET 2x to .NET 4.6 [https://blogs.unity3d.com/2016/12/13/unity-5-6-beta-is-now-available/](url)

Just food for thought I guess. Glad you guys are still working on the project. Good luck!

**Comment by mklingen** [comment]
@DanoThom wow looks familiar! So cool! Believe me, if I were to start this project over again this year I would pick Unity as a platform. However, I don't think doing that is appropriate at this stage in the project.

As for breaking up PlayState -- yes definitely its a long time coming. ComponentManager and ChunkManager should probably live inside another metaclass called Simulation or World or whatever. Keep in mind that all this would do is turn "World" into the giant megaclass that rules all rather than "PlayState", but I agree it belongs totally outside of the State class.

**Comment by yueranyuan** [comment]
@mklingen a significant portion of the code in PlayState refers to the GUI and the embarkment. Separating world, playstate (gui), and embarkment into separate classes could dramatically reduce the meganess of the World class.

Having the World class could also help us create test scenarios - obstacle courses to test dwarven AI etc.

**Comment by yueranyuan** [comment]
@Blecki, @mklingen are you guys looking to factor out the "World" or should I look into it myself

**Comment by Blecki** [comment]
If you're ready to go at it, go ahead. I'll stay out of it until the change is merged. It will make my job of refactoring the input much easier...

**Comment by yueranyuan** [comment]
@Blecki I'm planning to do it sometime in the next couple of days - if you want to do it before then though I can wait for you. Just tag me if you decide to go ahead and do it. If you do make changes to the GUI in PlayState in the meantime, we should still be able to merge fairly simply - the GUI functions seems relatively decoupled from the World functions

**Comment by mklingen** [comment]
@yueranyuan sounds like a good task to tackle.

**Comment by Blecki** [comment]
Most of the complexity was moved over to WorldManager instead. Ah well, lots of little steps will get us there.
