### ISSUE TITLE
Trader's items disappear on cancel.

### ISSUE THREAD

**Issue by BombBloke** [CompletelyFairGames/dwarfcorp#246]
When a trader arrives, initiate a trade, select some items in the trader's inventory, and then cancel. Return to the trade screen to find those items are no longer in the trade window nor in the trader's inventory window.

Doesn't seem to affect your own items, or money. Speaking of money, though, the "profit needed" value which is displayed in the lower left seems to go up and down at random when you change the amount of cash you ask for or offer.

**Comment by mklingen** [comment]
Hmm I think you're right. Cancelling doesn't reset the trader's resource state. As for the profit needed value, that is the correct behavior but maybe its confusing. That number is the total amount of profit they expect from the trade. If either your money or their money changes, the amount of profit also changes (but the percent remains fixed)

**Comment by BombBloke** [comment]
> If either your money or their money changes, the amount of profit also changes

I'm certainly confused - why would traders expect to make a profit on a trade of *money?*

It seems to me that if a trader wants to treat my *items* as being eg 25% less valuable than their items, then that's fair enough (but this would be more simply reflected by tweaking the item values shown in the trade windows). Treating my *money* as less valuable than theirs seems to invalidate the point of a common currency.

**Comment by mklingen** [comment]
I agree it's confusing. The trade is worth $x for them and $y for you (sum total of goods and money). They demand that $x >= $y + 25% * $y . That means if $y changes (even if its money, not goods), $x must also change.

The dollar amount of the goods shown in the window reflects how much *they are willing to pay for that item*. If you give them that exact amount in exchange for money, they will reject it, because they also want a 25% profit on top of that value. I'd have to do the math but perhaps just changing the apparent value on their side vs. your side would do the same thing.

**Comment by Blecki** [comment]
It may be simpler to separate 'sell' and 'buy'. So they only deal with coins and not actual object-for-object bartering. Loses some of the charm, though, of actual trading.

**Comment by BombBloke** [comment]
Object-for-object is fine, and cash-only trading would be outright prohibitive in cases where both sides lack the funds to deal with the goods on-hand. The main problem I have is that traders seem to think their money is somehow worth more than my money - if I offer $110 of mine for $100 of theirs (with no items involved), it's simply not rational for them to take it as an insult!

**Comment by mklingen** [comment]
I interpret that as their time is worth money (they traveled all the way to your colony after all), and if you're wasting their time by making them give you $100 for a $10 profit they will get angry.

**Comment by BombBloke** [comment]
Should they not then get even angrier if I make them leave without trading anything at all?

**Comment by mklingen** [comment]
Fair enough. I will make the profit only apply to items so that they buy items at less of a price than they sell items. That will implicitly take care of the issue. Then they will only demand that the trade is profitable and will only get offended if it is unprofitable or if you give them something offensive.

**Comment by BombBloke** [comment]
Thanks for your patience with me.  ;)  I do strongly believe that'll be a better system, though.

**Comment by mklingen** [comment]
This issue (trade cancelling) is now fixed. We can move the discussion over how the trade system works to an enhancement issue.
