### ISSUE TITLE
"Get Paid" task loop

### ISSUE THREAD

**Issue by Orangicus** [CompletelyFairGames/dwarfcorp#259]
Dwarf was in the spawned treasury, migrating my items and money to a new stockpile/treasury.
He stops moving after collecting his fill of items, and stays that way.
Check task in his profile; He is stuck on "get paid" - which alternates between "get paid" and any other tasks he is assigned to at the time, but always returns to "get paid" so that he doesn't move.
There is enough money to pay a 0-level dwarf in the treasury.
Had to cancel the "get paid" task, after which he finished transporting items and money to the new stockpile, but immediately caused issue #263.
[Update] This seems to have caused all of my money to disappear, as a result (the dwarf with the glitch was carrying all my money).

I presume he got stuck because he was already full of money and items and was trying to pick up therest of my gold to transport it.
As for the "get paid," does that not happen exclusively at "dawn" and at no other time?
Not sure why he was trying to get paid, otherwise.

![get paid](https://user-images.githubusercontent.com/22550054/30978079-530c35a0-a42e-11e7-8e67-f63725ca8170.gif)

**Comment by BombBloke** [comment]
Are you sure that one *particular* treasury contained enough money to pay the dwarf? I've had multiple dwarfs get stuck on "get paid" (where they simply sit in the middle of a treasury), and resolved it by simply ordering them to move to one with more money in it. No crash was encountered in my cases, nor did I need to cancel any orders to get the dwarves to move, but then, I haven't managed to figure out how to "move" stuff yet. The closest I've gotten to getting the "move" tool to do *anything* was to trigger a tooltip over a lamp stating "this bed is in use".

Dwarves will try to collect their pay after midnight, when it's announced how much you've "paid" them. Usually they're asleep and so they don't actually perform the task until 6am, but sometimes a dwarf will either wake early or never go to sleep at all, in which case they may also collect their earnings earlier.

Best I can make out, if a dwarf can't be paid because you're broke, they'll forget about the task. If you have the money somewhere, then they'll keep trying to collect their pay until they happen across a treasury with enough cash (always picking the closest treasury over and over even if it lacks the funds), but during this time I found that they can be ordered to go off and do something else. If I run into it again I'll check the task priority.

**Comment by Orangicus** [comment]
Well. I had one treasury. I built another treasury. Then, I moved all the money from where the one treasury was to the new treasury. So, yes, except during the moving process, which is when this occurred (as noted above).

**Comment by Orangicus** [comment]
As for how to move objects:
1. Go to menu for that item (the build menu of a craftdwarf only)
2. Select the compass icon.
3. To move object, left click.
4. To destroy the object, right click.

For zones and floors, you have to destroy them completely to move them.

**Comment by BombBloke** [comment]
> As for how to move objects:

What sort of "objects" should I expect that to work on? I've tried it on a variety of things with no visual response, other than the lamp I mentioned.

> Updated with GIF.

Interesting to see that your dwarf doesn't appear to be standing in a treasury, but rather he's within the ruins of a balloon port - does it still even count as a treasury in that state? I recall some reports that bulldozing the starter port has a high crash-rate attached to it, too.

**Comment by Orangicus** [comment]
The compass (edit) icon works on any object. Literally - any item under the menu labelled "objects" through menu navigation.
If you want to remove a treasury, select the treasury tool and right-click while selecting over the existing treasury.
Same thing with anything. Want to remove blocks? Go to the block menu. Select the type of block. Right click and select it.

The issue may or may not be related to #275 in some way

**Comment by mklingen** [comment]
I believe that this issue is fixed by this commit https://github.com/CompletelyFairGames/dwarfcorp/commit/231b2764e09d0f3dc05c87dc55742df3ab39dd5b
