### ISSUE TITLE
Dwarf inventories not getting emptied.

### ISSUE THREAD

**Issue by Orangicus** [CompletelyFairGames/dwarfcorp#292]
They just keep everything in there until they eat, it seems.
They go to sleep, they "look interesting" and anything else before they will dump their inventory into the stockpile.
Their inventories did not become full for me to test if they dump when their inventory is full (does it get full?).
They only dumped into the stockpile when they went to eat.

**Comment by BombBloke** [comment]
Dwarves should dump whenever they're idle, so long as there's store space. When they go to eat, that *creates* store space, so if they can't otherwise drop off stuff that'll allow them to stock at least *something*.

When your dwarves eat, are they dropping off one or two items, or are they sitting there for extended periods and offloading stuff en mass?

Bear in mind that currently, constructed stocks may not be registered as a valid place to store items (#257).

**Comment by Orangicus** [comment]
They do not dump when idle (that's why I made this issue).
They drop items en masse (they [two dwarves] dug a 20-block deep, 5x5 vertical tunnel without unloading at any time before eating).
This was while I had not attempted to edit the initial stockpile.

**Comment by BombBloke** [comment]
I wonder if your axe dwarf reserved the store space.

**Comment by Orangicus** [comment]
When he dumped all his stuff, it was only like three boxes, so probably not.

**Comment by mklingen** [comment]
believe this fixes it. https://github.com/CompletelyFairGames/dwarfcorp/commit/2940f9aff491eb723868117d14d7ed7050d3e26f
