### ISSUE TITLE
Mass Voxel selection can miss perfectly valid targets.

### ISSUE THREAD

**Issue by Solsund** [CompletelyFairGames/dwarfcorp#41]
Selecting voxels using the new method that only selects currently visible voxels can leave gaps in the selection.

In the example picture look at the row where the mouse cursor is found.  Those seven in that row are not selected and will not be destroyed.  The little three block row the dwarves are standing on in the shot also had this issue.  Near the very top are a few more that are surrounded on all sides except for the top face and are not selected.

Three rows up there is exactly the same voxel formation (a voxel blocked on all sides except for towards the camera) happening except those are selected just fine.

![image](https://cloud.githubusercontent.com/assets/6342605/22048256/53a3576e-dcf1-11e6-8dc6-4aef6c91db08.png)

**Comment by Blecki** [comment]
Is the goal here to select only the voxels the camera can actually see, or all the voxels that are on the 'surface'?

**Comment by mklingen** [comment]
Seems to be an issue with raycasting.

**Comment by Blecki** [comment]
That has it's own set of issues, but would be simple.

So are these being picked by shooting rays from the camera? How are the rays calculated?

**Comment by mklingen** [comment]
shoots a ray from the camera to a corner of the voxel and then traverses the ray using [this algorithm](http://www.cse.chalmers.se/edu/year/2011/course/TDA361/Advanced%20Computer%20Graphics/grid.pdf). If the ray hits another voxel before hitting the selected one it is considered "occluded". This will have the disadvantage of not being able to select partially occluded voxels. Same problem exists in the body selector #23. Both issues could be fixed by rendering a selection buffer to the GPU instead and selecting the pixels on the image.

**Comment by Blecki** [comment]
If it's using the exact corner, then we might be running into a precision issue where it's detecting the voxel immediately next to it as blocking it.

**Comment by mklingen** [comment]
Switched this for selecting voxels on the "surface". But raycasting bug still persists. I think its a logical error -- if the center of a voxel is occluded it does not necessarily mean the whole voxel is occluded.
