### ISSUE TITLE
"Using EXT_swap_control_tear VSync!" might not work on Linux laptops with an NVIDIA card.

### ISSUE THREAD

**Issue by bcmpinc** [CompletelyFairGames/dwarfcorp#440]
Is there a way to see the current FPS? Nvidia's optimus/prime drivers on Linux are notorious for not syncing to vsync even if it reports it does, and then causes games to run at 1000 FPS. See also:
https://bcmpinc.wordpress.com/2015/08/18/creating-an-opengl-4-5-context-using-sdl2-and-glad/#comment-307

**Comment by Blecki** [comment]
Yes, press f10. Be warned that the performance measurement stuff occasionally crashes the game because of a race condition.On Oct 27, 2017 7:07 AM, Bauke Conijn <notifications@github.com> wrote:Is there a way to see the current FPS? Nvidia's optimus/prime drivers on Linux are notorious for not syncing to vsync even if it reports it does, and then causes games to run at 1000 FPS. See also:
https://bcmpinc.wordpress.com/2015/08/18/creating-an-opengl-4-5-context-using-sdl2-and-glad/#comment-307

**Comment by Blecki** [comment]
Uh GitHub why you keep doing that?

**Comment by bcmpinc** [comment]
Ok, the FPS is capped at 60.
