### ISSUE TITLE
world is all water

### ISSUE THREAD

**Issue by teflon8** [CompletelyFairGames/dwarfcorp#445]
whenever I use the advanced world gen, if i change any of the settings from medium, (i.e. map size to large or caves to low)it always generates a water world, with only a few small volcano type islands to play on

**Comment by mklingen** [comment]
Hmm really? I will try it.

**Comment by mklingen** [comment]
I have tested this and unfortunately can't reproduce. It is possible that we've already fixed the issue, or it could be that you're using settings which make the world all water. Setting "Faults" or "Sea Level" or "Erosion" to very high will usually cause the world to become all water (but that's intentional)
