### ISSUE TITLE
[BUG] user told dwarf to place block, but nothing happened.

### ISSUE THREAD

**Issue by Immorthar** [CompletelyFairGames/dwarfcorp#510]
![20171224121956_1](https://user-images.githubusercontent.com/34803122/34323836-e25e996c-e8a5-11e7-84c2-72702378f8d7.jpg)
Noticed that dwarfs taking stone in their inventories, and then trying to place it, but when craft-bar is filled nothing happening and stone remains in their inventory.

**Comment by Sydonia** [comment]
Hey I had a similar problem. The issue with mine was I had a room with two doors one of the doors was through a room and the other was straight from the mine entrance. The one from the mine entrance however was blocked by a tile so it seems like the dwarf wanted to path through that door and even if I placed him inside the room to build the tiles he would just stand there because I think he was trying to path back to the resources to build the block. Not 100% sure if this is right but in my case once I cleared that door the dwarf place the blocks properly. So maybe the AI takes the path with the least amount of doors?

I really can't make out your screenshot, but I was placing dirt blocks for mushroom farming, haven't seen the same issue since.

**Comment by Sydonia** [comment]
Nevermind this issue has returned and is not related to pathing as far as I can tell now...

**Comment by mklingen** [comment]
Trying to reproduce. When you say the dwarf took the stone, does that mean it was something they picked off the ground, or was it something that came out of a stockpile?

**Comment by mklingen** [comment]
Okay, managed to track down, reproduce and fix this bug. Cause was that while getting assigned the task, the dwarf thought that it had resources in its inventory -- then, when actually trying to build the floor, the resource got marked as invalid because it was supposed to be gathered, rather than used for a task.

Fixed by allowing the user to re-mark the resource as being used for a task while building floors/walls.

**Comment by Sydonia** [comment]
Thanks a lot for fixing this and thanks for taking the time to create this
game. I really enjoy the time I spend with it.
