### ISSUE TITLE
[BUG] when there are no beds available, an unconscious near-death dwarf gets frozen.

### ISSUE THREAD

**Issue by Sydonia** [CompletelyFairGames/dwarfcorp#516]
During a small skirmish on of my dwarfs was reduced to 0 health but did not die. This resulted in the dwarf constantly trying to heal themselves but they were unable. I'm not sure if I could have sent another dwarf to try and help since I have no idea how to do that and also I'm not sure what items might be needed to heal a dwarf. The dwarf in question would not move or accept other orders, but would constantly try to heal self and fail then try again.

Sorry no screenshot as it's from an old save. I wasn't sure if this was working as intended to be honest so I didn't report it at first. This was from the Dec. 24th build.

**Comment by mklingen** [comment]
The dwarf is actually unconscious, but the animation apparently isn't working. He will stay unconscious until either he dies or his HP naturally increases above a threshold. If a bed is available he will go to the bed and try to heal there. This should be more clear.

**Comment by mklingen** [comment]
This has been fixed by some of my latest changes. will be in the next release. New rules for dwarf death are as follows;

1) If health falls below 15, look for a bed to sleep in until healed (.10 HP healed per second)
2) If health falls below 5, fall unconscious and sleep until healed (.01 HP healed per second)
3) If damaged while unconscious and health is 0, die.
