### ISSUE TITLE
Error compiling: ParticleEmitter does not implement FrustumCull.

### ISSUE THREAD

**Issue by eurabilis** [CompletelyFairGames/dwarfcorp#533]
I should start off by saying I have no idea what I am doing I am not a programmer. But I wanted this game and the idea of being able to compile it myself intrigued me so I installed visual studio, and although I had a small battle, I did get it to compile after doing some things, and I could play the game. However that was with vs 2013. I since have vs 2017 also, and was trying to get it to compile on that but couldn't get it to. Long story short I don't know if it's something I did, or if it's something with todays code but with the latest as of 7pm 1/15, I get 9 of these errors.

`Error	76	'DwarfCorp.ParticleEmitter' does not implement interface member 'DwarfCorp.IRenderableComponent.FrustumCull'	D:\CODE\SRC\dwarfcorp-master\DwarfCorp\DwarfCorpXNA\ParticleEffects\ParticleEmitter.cs	134	18	DwarfCorpXNA
`

I know you probably don't have time for my BS, but can I get some help? Can you at least tell me if the problem is just todays code or if its something I installed trying to get it to work on 2017? Because like I said now I get the above error on vs 2013, and vs 2017 wont even open the project it says its incompatible. Thank you in advance for any help. GREAT GAME!

**Comment by Blecki** [comment]
Kind of looks like you got a partial set of changes. I'm using 2017 myself so it is possible to compile it. Are you on the discord?On Jan 15, 2018 7:25 PM, mike <notifications@github.com> wrote:I should start off by saying I have no idea what I am doing I am not a programmer. But I wanted this game and the idea of being able to compile it myself intrigued me so I installed visual studio, and although I had a small battle, I did get it to compile after doing some things, and I could play the game. However that was with vs 2013. I since have vs 2017 also, and was trying to get it to compile on that but couldn't get it to. Long story short I don't know if it's something I did, or if it's something with todays code but with the latest as of 7pm 1/15, I get 46 of these errors.
Error 76 'DwarfCorp.ParticleEmitter' does not implement interface member 'DwarfCorp.IRenderableComponent.FrustumCull' D:\CODE\SRC\dwarfcorp-master\DwarfCorp\DwarfCorpXNA\ParticleEffects\ParticleEmitter.cs 134 18 DwarfCorpXNA
I know you probably don't have time for my BS, but can I get some help? Can you at least tell me if the problem is just todays code or if its something I installed trying to get it to work on 2017? Because like I said now I get the above error on vs 2013, and vs 2017 wont even open the project it says its incompatible. Thank you in advance for any help. GREAT GAME!

**Comment by eurabilis** [comment]
No how do I join Ill join now. Thanks.

**Comment by mklingen** [comment]
This is related to a fix I just made today that was causing particles not to get drawn on master.

**Comment by eurabilis** [comment]
Great! Thanks for the response that's good to know that it wasn't on my end. As I said I was trying to get it to compile in VS 2017 and it made some changes then all of a sudden it wouldnt compile on neither. Works now. Thanks for the good work!
