### ISSUE TITLE
AI: Dwarves don't avoid lava

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#698]
![image](https://user-images.githubusercontent.com/6562812/39776152-f6b5c830-52cd-11e8-8c84-1057baef9603.png)

Dwarves don't know that they should avoid lava. When directed to find their path to the other side of a bit of lava, they will march straight through.

126d7ff8

**Comment by mklingen** [comment]
not saying it's correct!

**Comment by mklingen** [comment]
Okay fixed in master. 
![no_lava](https://user-images.githubusercontent.com/241184/39845356-5bd09b3c-53c3-11e8-9b6e-25402ab26883.png)

**Comment by com1clyf3** [comment]
Dwarfs exit balloon port and enter lava, despite having a clearer safe path.
[Crimeia_524_131733910608977844.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/2099557/Crimeia_524_131733910608977844.zip)
[Crimeia.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/2099560/Crimeia.zip)

3eea47e7

**Comment by mklingen** [comment]
Likely they are falling into the lava by accident... they still try to avoid lava when pathfinding.

**Comment by com1clyf3** [comment]
I observed one climbing down a ladder into the lava, so not crazy accidental.

Otherwise, yeah, pathfinding still works.

**Comment by mklingen** [comment]
I took a look at this save. Fixed a bug which caused lava not to spawn based on this save. Also made it so that ladders light on fire when exposed to lava, and grass gets destroyed.

As for dwarfs avoiding lava, what's going on here is that the dwarves are randomly wandering when idle, and might randomly fall off into the lava. I made them put in a check so as to not want to walk toward lava while wandering, but it will still happen from time to time.

I also made dwarves freak out and run around while on fire.
