### ISSUE TITLE
New trade screen issues.

### ISSUE THREAD

**Issue by mklingen** [CompletelyFairGames/dwarfcorp#807]
- [x] Molemen crashes because the language of molemen is defined as "Moleman" when it should be defined as "Molemen". Make sure we test every race's trade interactions.
- [x] Goblin language also misdefined and causes crash.
- [x] While trading with Goblin "unknown command $finalize_trade". Seems "finalize_trade" is just not in the list of commands.
- [x] While trading with Elf, "I am snowflake, seeker of null" (EDIT: seems all envoys say "null" for their faction name. Necromancers seem to sometimes have the name "Elf")
- [x] Text overflows the bottom of the text panel.
- [x] In Moleman conversation: undefined reference to command $increment_offensive_trades"
- [x] Trader was supposed to tell you about good and bad trades while on the trade screen. Trader no longer does this.
- [ ] Traders are supposed to tell you why your relationship is good or bad, they no longer do this.
- [x] 2nd person narrative is intermixed with 1st person phrases, yet the character says all of these phrases. This is especially disconcerting for molemen. Granted it was this way before, but the 3rd person narration was in angle brackets.
- [x] Trade screen should use 1x fonts, particularly it should use "font10" for the text and possibly the options.
- [x] Dialogue box for the trade screen should use the speech bubble border.
- [x] Speaker needs a dark border.
- [x] History of conversation is not necessary. It only causes there to be too much text on screen at once. Keep text on screen to one line at once.
- [x] Player should be able to interrupt speaker immediately by pressing a key.
- [x] When the player says "End Conversation" the state of the trade envoy *should not change* they should remain at the balloon port for further trades.
- [x] Traders are supposed to leave after 3 offensive trades. They currently do not... however they end up declaring war on you if you submit too many offensive trades. They don't inform the user of this.

**Comment by mklingen** [comment]
I have fixed the first two crashes and pushed to master.

**Comment by mklingen** [comment]
fixed "finalize_trade" and "increment". "increment" is just not a yarn command, it's supposed to be implemented as an explicit expression. "finalize_trade" had the incorrect signature. Recommend a runtime check to make sure all the Yarn commands have the correct signature.

**Comment by mklingen** [comment]
Fixed faction name, it was supposed to be called "$envoy_faction" not "$faction_name"

**Comment by mklingen** [comment]
Got the aesthics mostly how I wanted. Fixed the framerate of the speaker. Added any-key-to-skip-line feature.

**Comment by mklingen** [comment]
Fixed text overflow. Widget was using `Rect` instead of `GetDrawableInterior`

**Comment by mklingen** [comment]
Fixed deeply embedded bug in YarnSpinner. `Value.cs` had incorrect copy constructor. I also made text move a bit faster.

**Comment by ferry-** [comment]
Another issue: clicking "Stop Trading" while the speaker widget is showing (after a successful trade or such), causes `YarnEngine::Unpause` to throw `InvalidOperationException` because the state is still `Speaking`. I couldn't figure out how to interrupt the current speech - simply setting the state to `paused` in the lambda in `DwarfCorp.YarnState.WaitForTrade` causes the original speech to freeze, after which the window hides after the normal timeout. I have to press "stop trading" again to trigger the line and have it close. I'd like to have it immediately stop the original speech, deliver the "stop trading" line and close.

Another issue is that shift-clicking an item of adds a single item to the offer list (when there are no items of that type already offered), but removes 5 items from the stock. I don't know if the 4 items are truly gone.

Yet another (smaller) issue is that the trader responds to "Stop Trading" with a "why are you wasting my time?" response whether a successful trade occurred just before or not. It would make sense to have a variety of responses based on how much value of goods was exchanged.

**Comment by mklingen** [comment]
> Another issue: clicking "Stop Trading" while the speaker widget is showing (after a successful trade or such), causes YarnEngine::Unpause to throw InvalidOperationException because the state is still Speaking.

Fixed in master to the extent that you described, no longer crashes, but the speech times out and you hit "stop trading" again. Good enough for now.

> Another issue is that shift-clicking an item of adds a single item to the offer list (when there are no items of that type already offered), but removes 5 items from the stock. I don't know if the 4 items are truly gone.

This is now fixed in master.

> Yet another (smaller) issue is that the trader responds to "Stop Trading" with a "why are you wasting my time?" response whether a successful trade occurred just before or not. It would make sense to have a variety of responses based on how much value of goods was exchanged.

That's correct, we just haven't implemented that logic yet in the new conversation system.

**Comment by com1clyf3** [comment]
This looks all fixed. Close? @mklingen
