### ISSUE TITLE
AI: Dwarves get stuck floating in gamble

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#834]
Not totally sure of exact repro, but seems to happen naturally. Canceling gamble task does not fix it.  I'd just play the game for five to fifteen minutes.  Alternatively, you can load the save from #831 .

![image](https://user-images.githubusercontent.com/6562812/45186758-908f8580-b1fc-11e8-97f7-2afb5cbbd343.png)

a6e468d2

**Comment by mklingen** [comment]
I believe this is caused by my logic for gambling assuming that the dwarves are on more or less flat ground. If the dwarf ends up stuck behind an obstruction or in the air, they will keep sitting there until the gambling session has ended. I think I will try to make some sanity checks on the gambling to cancel it when these situations arise.

**Comment by mklingen** [comment]
dwarfs now quit gambling when there is nothing underneath them. Haven'tested thoroughly.

**Comment by com1clyf3** [comment]
This hasn't occurred for a month, so closing.
