### ISSUE TITLE
Feature: Diplomacy - Raids, Peace, Trade 

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#848]
- Traveling is much shorter than the estimates given. 3 days travel happens in 3/4s of a day.
- Sent off my raiding group with no food, and they traveled hundreds of miles with no problem. During the raid, they got 10 food resources. Then on the way back they all died of starvation, even though they had lots of resources left. So at least one bug in there. 
- One of my dwarves was captured during a raid. Seems natural that'd we allow the player to get that dwarf back. Maybe add it on to options during the peace process? Or we could make it an event?
- Does it matter who, how many, or what types of dwarves that you send? If I send nothing but muskets on a peace mission, will it fail?
- Got this error when my peace mission reached their destination:
![image](https://user-images.githubusercontent.com/6562812/45574491-3450e500-b83e-11e8-908e-29b963a045a1.png)
-Are the ellipses in the GUI supposed to be progress bars? I notice that when I click in, one seems like it's supposed to be filling in. Looks like this "I....." Never fills in more than that though.

**Comment by mklingen** [comment]
> Traveling is much shorter than the estimates given. 3 days travel happens in 3/4s of a day.

That's fixed.

> Sent off my raiding group with no food, and they traveled hundreds of miles with no problem. During the raid, they got 10 food resources. Then on the way back they all died of starvation, even though they had lots of resources left. So at least one bug in there.

The way starvation works, this sounds entirely possible. Dwarves lose health due to starvation. They probably got knocked down to near zero health, did their raid (lost a little more health), and then on the way back used up their food reserves and died. I've made the announcer tell you more about what's happening with starvation. It could be redesigned.

> -Are the ellipses in the GUI supposed to be progress bars? I notice that when I click in, one seems like it's supposed to be filling in. Looks like this "I....." Never fills in more than that though.

Yes, and they do get filled correctly now.

> One of my dwarves was captured during a raid. Seems natural that'd we allow the player to get that dwarf back. Maybe add it on to options during the peace process? Or we could make it an event

I agree that would be cool, I don't know quite how to make that possible at the moment.

> Does it matter who, how many, or what types of dwarves that you send? If I send nothing but muskets on a peace mission, will it fail?

Yes. Peace/trade missions depend on high charisma. Raid missions depend on strength/dex. Musket/axedwarves have lower charisma so there is actually a higher chance that the peace mission will fail, and trades will be slightly lower yield. This can all be balanced better though.

**Comment by mklingen** [comment]
Fixed the crash as well.

**Comment by com1clyf3** [comment]
Closing.
