### ISSUE TITLE
Walk Mode: Minimized while in paused walk mode will break mouse

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#851]
Not 100% on repro. Everything works out except for three. Eitherway, should work if you try the repro three or for times.

1. New game.
2. Enter walk mode.
3. Go for  a walk to a low part of the map/go for a walk for a little while.
4. Pause game.
5. Minimize game.
6. Move mouse. Observe that your mouse icon is now stuck to the side of your screen, and you will have to exit the game via Task Manager in order to escape bug.

bdac6426

**Comment by mklingen** [comment]
Fixed in master. Forensics: in overhead mode, pressing shift rotates, and its impossible to minimize while shift is pressed. The opposite is true in walk mode. The game only captures the shift key when the mouse is over the game, so if you minimize, you won't be able to turn off the rotation mode (which prevents the mouse from moving).

Fixed by having it check to see if the game is minimized or the mouse isn't over the screen area, and if so it doesn't do the rotation.
