### ISSUE TITLE
Build: Crafter facing opposite direction of zone they're building

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#877]
![image](https://user-images.githubusercontent.com/6562812/46377479-ac087780-c666-11e8-9f28-a6721c896cf7.png)

1. Set up a variety of zones
2. Observe crafter build. Observe that they face the opposite direction of the zone they're building.  Also observe the building animation will appear in the zone behind them.

[Family Reaches_4_131829882820013533.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/2439723/Family.Reaches_4_131829882820013533.zip)
[Family Reaches.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/2439724/Family.Reaches.zip)

e8d2312b

**Comment by mklingen** [comment]
I've forced dwarves to face whatever direction they are hitting. Before, they would just face whatever direction the path planner had them at, which might have been in a random direction. Note that this new logic will sometimes force dwarfs to face sideways because the artwork only knows about 90 degree increments.
