### ISSUE TITLE
Unknown crash in full screen.

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#934]
![image](https://user-images.githubusercontent.com/6562812/46980387-64401200-d0a2-11e8-84ab-118666da7fa7.png)

I can get a repro by playing normally in fullscreen for about ten minutes or so.

1. Play the game.
2. Game crashes to desktop.
3. Win10 alert appears as shown in screencap above

b089ea7a

**Comment by Blecki** [comment]
Close version.txt and try again. That pop up has nothing to do with the
crash.

**Comment by com1clyf3** [comment]
As far as I can tell it's mainly to do with being fullscreen. PC has been giving res alerts when going fullscreen. This pop up appears every time at crash.  This does not happen when windowed, though there are odd res things happening there as well. #935

**Comment by mklingen** [comment]
I see that you're playing the game in release mode. Please play the game in debug mode and try to reproduce this crash. You'll likely find the real error. What it looks like to me is that the game has crashed for an unrelated reason, and since you're in release mode it's not going to break to the error in visual studio. The popup is unrelated. My guess is the thing in the bottom right is also unrelated.

**Comment by com1clyf3** [comment]
So far have not had the crash repro in release mode.

**Comment by com1clyf3** [comment]
No longer occurring in 77e0c8e8
