### ISSUE TITLE
1366 x768 monitors in windows 10 are too small to play the game in windowed mode.

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#935]
All available windowed options are too long, causing a portion of the bottom of the GUI to be overlapped and hidden by the windows taskbar.

b089ea7a

**Comment by mklingen** [comment]
I hadn't considered players might be playing the game on such a tiny resolution screen. The fix for this will have to be twofold 1) limiting the *WIDTH* of allowed resolutions instead of the *HEIGHT*. 2) moving the "Apply" button to the top of the screen.

The rest is just a problem with Windows, not with DwarfCorp, as any application with a fixed resolution would have this problem. Perhaps in windowed mode we should allow window resizing, but that would be a very very intrusive feature that would require a lot of engine rewrite.

**Comment by com1clyf3** [comment]
You might also want to allow the player to move the game GUI to the top, if that's not an expensive feature.

**Comment by mklingen** [comment]
I have reduced the allowed resolutions. Still have to consider moving the "Apply" button to the top. I will consider other fixes but I have to prioritize other bugs atm.

**Comment by mklingen** [comment]
I have also moved the "Apply" button to the top.
