### ISSUE TITLE
Trade: Undead trade envoy broken

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#959]
[Giruholand.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/2512384/Giruholand.zip)
[Giruholand_34_131848894127182354.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/2512387/Giruholand_34_131848894127182354.zip)

Save is from first natural occurrence. Undead arrived to balloonport, but never triggered trade event. Upon loading the save, the trade event is actually triggered. 

1. New game
2. God mode undead trade envoy
3. Observe that they are unable to spawn and/or trigger trade event

cf5eaf96

**Comment by mklingen** [comment]
The factions "Undead", "Elf", "Moleman" etc. are debug factions that shouldn't be used. Instead you should be spawning real factions. Undead factions have names like "X's Tower", "X's Grippe", "Empire of Death", "Dead Man's Hollow" etc. When you spawn a trade envoy from "Undead" they won't trade with you because that debug faction is set up to fight dwarfs automatically.
