### ISSUE TITLE
New Game: Loading two new games in a row will break terrain render

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#963]
This only happens with new games. If I load an older save, I'm note receiving this bug.

1. Start new/advanced game.
2. Quit to main menu.
3. Start another new game.
4. Observe terrain doesn't render.

77e0c8e8

**Comment by mklingen** [comment]
Happens all the time?

**Comment by mklingen** [comment]
Haven't been able to reproduce so far..

**Comment by com1clyf3** [comment]
![image](https://user-images.githubusercontent.com/6562812/47670436-87c78a00-db83-11e8-9623-5037e17e9f19.png)


Still occurring 4aabbfbb


Here's a save of it happening. Let me know what other data I can provide, if this doesn't help for some reason.
[Sea of Process.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/2526479/Sea.of.Process.zip)
[Sea of Process_385_131853097087160481.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/2526482/Sea.of.Process_385_131853097087160481.zip)

**Comment by mklingen** [comment]
Yes.

**Comment by mklingen** [comment]
Fixed in master. This was a subtle one. The chunk generation thread was not being exited cleanly. For whatever reason, in Release mode this was causing problems but not in Debug mode. I have also changed the way we deal with console output so that we can debug these issues easier in Release mode in the future. All log output is now mirrored to the console as well as to the log file.
