### ISSUE TITLE
Cook xN leads to more than N operations

### ISSUE THREAD

**Issue by kirill-stepanoff** [CompletelyFairGames/dwarfcorp#980]
version 18.11.21
When cook xN order (N>2) is iterated after cooking completes it spawns N-1 orders "cook x(N-1)", ..., "cook x1".

Example:
15 cooking operations as result of "cook x5" order:
Step 1:
Cook X5
Step 2:
Cook X4, Cook X3, Cook X2, Cook X1
Step 3:
Cook X3, Cook X2, Cook X1,Cook X2, Cook X1
Step 4:
Cook X2, Cook X1, Cook X1
Step 5:
Cook X1

On x10 order there would be hundreds of operations.

**Comment by mklingen** [comment]
Oh my God that's stupid. I will fix that!

**Comment by mklingen** [comment]
Actually it's not as bad as it sounds, they're just named weird. "Cook xN" means "cook one thing. This is the Nth time that the thing will be cooked". So they actually do this correctly.

I've changed the way repeats work so that they're named "Cook (k/N)" where k is the current iteration and N is the total, to make this clearer.
